name: Upload on new tags

on:
  push:
    tags:
      '*'

permissions:
  contents: write
  packages: write
  actions: write
  deployments: write
  issues: write
  pull-requests: read

jobs:
  buildAndUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v3.1.2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install scons markdown
          sudo apt update
          sudo apt install gettext

      - name: Build pot template
        run: scons pot

      - name: Build add-on
        run: scons

      - name: Calculate sha256
        run: sha256sum *.nvda-addon >> changelog.md

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            *.nvda-addon
            *.json
            *.pot
          body_path: changelog.md
          prerelease: ${{ endsWith(github.ref, '-dev') }}

      - name: Submit NVDA Add-on
        id: submit_addon
        uses: beqabeqa473/submitNVDAAddon@v1
        with:
          addon_name: "consoleLog"
          addon_version: "${{ github.ref_name }}"  # Usa el nombre del tag como versión
          download_url: "https://github.com/nvda-es/consoleLog/releases/download/${{ github.ref_name }}/consoleLog-${{ github.ref_name }}.nvda-addon"
          token: ${{ secrets.USER_TOKEN }}
          